platform: linux
image: docker:///docker

inputs:
    - name: prometheus
run:
    path: docker
    args: ["-H", "tcp://172.17.0.1:2375", "build", "-t", "prometheus", "-f", "prometheus/docker/Dockerfile", "prometheus"]
