resources:
    - name: prometheus
      type: git
      source:
        uri: git@github.com:ThoughtWorksInc/sp-prometheus.git
        branch: master
        private_key: {{private_key}}
    - name: registry
      type: docker-image
      source:
        repository: 10.202.128.51/projects/prometheus
        insecure_registries: [10.202.128.51]

jobs:
    - name: build-prometheus-image
      public: true
      plan:
        - get: prometheus
          trigger: true
        - put: registry
          params:
            build: prometheus
            dockerfile: prometheus/docker/Dockerfile


